config/routes.rb
HootsApp::Application.routes.draw do
  
  devise_for :users, controllers: {:omniauth_callbacks => "omniauth_callbacks"}

  devise_scope :user do
    # get '/users' => 'users#index'
    resources :users, :only => [:index] do
      member do
        get :my_posts
        get :favourites
        put :assign_favourite_user
      end
    end
  end



  root :to => "slideshow#index"

  resources :posts do 
    member do
      put :vote
      put :assign_favourite_post
    end
    resources :comments
  end
  resources :searches, only: [:create]

  # resources :messages, only: [:new, :create]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :posts
  has_many :comments
  has_many :scores
  has_many :stars
  has_many :providers

  validates :name, presence: true
  validates :email, presence: true

  mount_uploader :image, ImageUploader

  devise :database_authenticatable, 
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable,
         :timeoutable, 
         :omniauthable, 
         :confirm_within => 10.minutes,
         :omniauth_providers => [:google_oauth2, :facebook]


  # Setup accessible (or protected) attributes for your model

  attr_accessible :name, :image, :role, :email, :password, :password_confirmation, :remember_me, :encrypted_password, :reset_password_token, :reset_password_sent_at, :remember_created_at, :sign_in_count, :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :confirmation_token, :confirmed_at, :confirmation_sent_at, :unconfirmed_email, :provider, :uid, :fav_users, :fav_posts, :user_favs, :phone_no

  def self.from_omniauth(auth)
    if user = User.find_by_email(auth.info.email)
      user.provider = auth.provider
      user.uid = auth.uid
      user
    else
      where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.skip_confirmation!
        user
          #don't require email confirmation
      end
    end
  end

  def role?(r)
    self.role == r.to_s
  end

  include Gravtastic
  gravtastic

  def destring(user)
    fav_posts = user.fav_posts[1..-2].split(',').collect! {|n| n.to_i}
    return fav_posts
  end
  
  def destring_user(user)
    fav_users = user.fav_users[1..-2].split(',').collect! {|n| n.to_i}
    return fav_users
  end

  def destring_favs(user)
    user_favs = user.user_favs[1..-2].split(',').collect! {|n| n.to_i}
    return user_favs
  end

end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  # GET /users
  # GET /users.json

  before_filter :authenticate_user!, except: [:index]
  # authorize_resource

  def index
    users = User.all
    total_score = 0
    users.each do |user|
      total_score = 0
      scores = [0]
      user.posts.each do |post|
        total_score = total_score + post.score
        scores << post.score
      end
      user.score = total_score
      user.top_score = scores.max
    end
    @users = users.sort_by{ |a| a.score }.reverse
  end

  # def assign_favourite_user
  #   fav_user = User.find(params[:id])
  #   curr_user = User.find(current_user.id)

  #   fav_users = curr_user.destring(curr_user)
  #   fav_users.push(fav_user.id)
  #   curr_user.fav_users = fav_users.to_s
  #   curr_user.save
  # end


  def favourites
    curr_user = User.find(current_user.id)
    fav_posts = curr_user.destring(curr_user)
    fav_users = curr_user.destring_user(curr_user)
    @top_posts = []
    @top_users = []
    fav_posts.each do |n|
      post = Post.find(n)
      @top_posts << post
    end
    fav_users.each do |n|
      user = User.find(n)
      @top_users << user
    end
    render :favourites
  end

  def assign_favourite_user
    fav_user = User.find(params[:id])
    curr_user = User.find(current_user.id)
    fav_users = curr_user.destring_user(curr_user)
    user_favs = fav_user.destring_favs(fav_user)
    respond_to do |format|
      if fav_users.include?(params[:id].to_i)
        format.html { redirect_to favourites_user_path, notice: "That user is already on of your favoorites!" }
      else
        fav_users.push(params[:id].to_i)
        curr_user.fav_users = fav_users.to_s        
        curr_user.save
        user_favs.push(current_user.id)
        fav_user.user_favs = user_favs.to_s
        fav_user.save
        format.html { redirect_to favourites_user_path, notice: "You've added to your favoorites." }
      end
    end
  end

  def my_posts
    @posts = Post.where(user_id: current_user)
  end



  # GET /users/1
  # GET /users/1.json
  # def show
  #   @user = User.find(params[:id])
  # end

  # GET /users/new
  # GET /users/new.json
  # def new
  #   super
  # end

  # GET /users/1/edit
  # def edit
  #   @user = User.find(params[:id])
  # end

  # POST /users
  # POST /users.json
  # def create
  #   super
  #   @user.role = 'user'
  #   @user.save
  #   @user = User.new(params[:user])
  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #     else
  #       format.html { render action: "new" }
  #     end
  #   end
  # end

  # PUT /users/1
  # PUT /users/1.json
  # def update
  #   @user = User.find(params[:id])

  #   respond_to do |format|
  #     if @user.update_attributes(params[:user])
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /users/1
  # DELETE /users/1.json
#   def destroy
#     @user = User.find(params[:id])
#     @user.destroy

#     respond_to do |format|
#       format.html { redirect_to users_url }
#       format.json { head :no_content }
#     end
#   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  
  .field_image
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing hootster

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/favourites.html.haml
.container-favs
  .favs-container-1
    %h2 Favourite Hoots
    - @top_posts.each do |post|
      .post-break
        %hr
      .post-score
        = "#{post.score}"
      .post-comment
        = link_to post.content, post
      .post-commentcount
        = "Comments: #{post.comment_count} | #{post.user.name}"
    .post-break
      %hr

  .favs-container-2
    %h2 Favourite Hootsters
    %ul
      - @top_users.each do |user|
        %li
          =user.name

%footer.footer-bar
  %hr
  .footer-link-right
    = link_to 'View Index', posts_path

app/views/users/index.html.haml
.container-leaderboard
  .leaderboard
    %h2 Hootsterboard

    %ol
      - @users.each do |user|
        %li
          .user
            =user.name
            \- total score:
            =user.score
            \| top scoring hoot:
            =user.top_score
          .user-score
            = link_to image_tag('PNG/heart.png'), assign_favourite_user_user_path(user), method: :put

%footer.footer-bar
  %hr
  .footer-link-right
    = link_to 'View Index', posts_path

app/views/users/my_posts.html.haml
.container-myposts
  .my-posts-container
    %h2 My Hoots
    - @posts.each do |post| 
      .post-break
        %hr
      .post-score
        = "#{post.score}"
      .post-comment
        = link_to post.content, post
      .post-commentcount
        = "Comments: #{post.comment_count}"
    .post-break
      %hr

%footer.footer-bar
  %hr
  .footer-link-right
    = link_to 'View Index', posts_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path