config/routes.rb
HootsApp::Application.routes.draw do
  
  devise_for :users, controllers: {:omniauth_callbacks => "omniauth_callbacks"}

  devise_scope :user do
    # get '/users' => 'users#index'
    resources :users, :only => [:index] do
      member do
        get :my_posts
        get :favourites
        put :assign_favourite_user
      end
    end
  end



  root :to => "slideshow#index"

  resources :posts do 
    member do
      put :vote
      put :assign_favourite_post
    end
    resources :comments
  end
  resources :searches, only: [:create]

  # resources :messages, only: [:new, :create]
end

app/models/post.rb
class Post < ActiveRecord::Base

  attr_accessible :content, :image, :geostamp, :flag, :score, :upvoters, :downvoters

  belongs_to :user
  has_many :comments
  has_many :scores
  has_many :stars

  validates :content, presence: true
  
  mount_uploader :image, ImageUploader

  self.per_page = 2

  def deserialize(post)
    @post = post
    upvoters = @post.upvoters[1..-2].split(',').collect! {|n| n.to_i}
    downvoters = @post.downvoters[1..-2].split(',').collect! {|n| n.to_i}
    return upvoters, downvoters
  end

  def comment_count
    comments.count
  end

  def send_texts(current_user, content)
    curr_user = User.find(current_user.id)
    tel_numbers = curr_user.destring_favs(curr_user)
    tel_numbers.each do |id|
      user = User.find(id)
      TextMessage.new("#{curr_user.name} says #{content}", user.phone_no.to_s).send
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json

  before_filter :authenticate_user!, except: [:index, :show]
  #authorize_resource

  def index
    @top_posts = Post.order("score DESC").limit(20)
    @latest_posts = Post.order("created_at").limit(20)
    # .paginate(:page => params[:page])
      respond_to do |format|
        format.html
        format.js 
      end
    @posts = Post.all 
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    authorize! :edit, @post
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user = current_user
    @post.score = 0
    @post.upvoters = "[-1]"
    @post.downvoters = "[-2]"
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end

    if params[:promote]
      curr_user = User.find(current_user.id)
      tel_numbers = curr_user.destring_favs(curr_user)
      tel_numbers.each do |id|
        user = User.find(id)
        TextMessage.new("#{curr_user.name} says #{params[:post][:content]}", user.phone_no.to_s).send
      end
    end

  end


  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    authorize! :update, @post

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
    end
  end

  def vote
    @post = Post.find(params[:id])
    @upvoters, @downvoters = @post.deserialize(@post) #converts upvoters and downvoters from strings to arrays

    #logic for votes
    if (@upvoters.include? current_user.id) && (params[:score] == "1") then
      @post.score -= 1 
      @upvoters.delete(current_user.id)
    elsif (@upvoters.include? current_user.id) && (params[:score] == "-1") then
      @post.score -= 2
      @upvoters.delete(current_user.id)
      @downvoters.push(current_user.id)
    elsif (@downvoters.include? current_user.id) && (params[:score] == "1") then
      @post.score += 2
      @downvoters.delete(current_user.id)
      @upvoters.push(current_user.id)
    elsif (@downvoters.include? current_user.id) && (params[:score] == "-1") then
      @post.score += 1
      @downvoters.delete(current_user.id)
    elsif !(@downvoters.include? current_user.id) && !(@upvoters.include? current_user.id) then
      case params[:score]
      when "-1"
        @post.score -= 1
        @downvoters << current_user.id
      when "1"
        @post.score += 1
        @upvoters << current_user.id
      end
    end
    
    @post.upvoters = @upvoters.to_s
    @post.downvoters = @downvoters.to_s
    respond_to do |format|
      if @post.save
        if params[:returnto] == "index"
          format.html { redirect_to posts_path, notice: "You've voted! Thanks." }
        else
          format.html { redirect_to @post, notice: "You've voted! Thanks." }
        end
      else
        format.html { redirect_to @post, notice: "Oops something went wrong, please try again" }
      end
    end
  end

  def assign_favourite_post
    curr_user = User.find(current_user.id)
    fav_posts = curr_user.destring(curr_user)
    respond_to do |format|
      if fav_posts.include?(params[:id].to_i)
        format.html { redirect_to favourites_user_path, notice: "That post is already on of your favoorites!" }
      else
        fav_posts.push(params[:id].to_i)
        curr_user.fav_posts = fav_posts.to_s        
        curr_user.save
        format.html { redirect_to favourites_user_path, notice: "You've added to your favoorites." }
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg


  %ul.slides-container    
    %li#new_post
      .post-container
        .post-contrast
          %p#post-text
            Hoot

  .field
    = f.text_area :content, placeholder: "Hoot..."

  .field
    = f.label :image
    = f.file_field :image
    #digits-left Digits left: 141
  .actions
    %input{:type => "submit", :value => "Save", :class => "button", :id => "post_submit"}

app/views/posts/_newform.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg


  %ul.slides-container    
    %li#new_post
      .post-container
        .post-contrast
          %p#post-text
            =@post.content

  .field
    = f.text_area :content, :size => '30x5', placeholder: "Hoot..."
  .field
    = f.label :image
    = f.file_field :image
    #digits-left
  .actions
    %input{:type => "submit", :value => "Publish", :class => "button", :id => "post_submit", :content => :content, :name => 'publish'}
    %input{:type => "submit", :value => "Promote", :class => "button", :id => "post_submit", :content => :content, :name => 'promote'}

app/views/posts/_updateform.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg


  %ul.slides-container    
    %li#new_post
      .post-container
        .post-contrast
          %p#post-text
            =@post.content

  .field
    = f.text_area :content, :size => '30x5', placeholder: "Hoot..."

  .field
    = f.label :image
    = f.file_field :image
    #digits-left
  .actions
    %input{:type => "submit", :value => "Save", :class => "button", :id => "post_submit"}

app/views/posts/edit.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg


  %ul.slides-container    
    %li#new_post
      .post-container
        .post-contrast
          %p#post-text
          

  #post-input
    .field#post-text-area
      = f.text_area :content, :size => '30x5', placeholder: "Hoot..."

    .field#post-image-box
      = f.label :image
      = f.file_field :image
      #digits-left
    .actions
      %input{:type => "submit", :value => "Save", :class => "button", :id => "post_submit"}

app/views/posts/index.html.haml
%section.container


  .top-posts-container
    %h2 Top Hoots
    - @top_posts.each do |post| 
      .post-break
        %hr
      .post-score
        = "#{post.score}"
      .post-comment
        = link_to post.content, post
      .post-comment-stats
        = "Comments: #{post.comment_count} | #{post.user.name}"
      / .post-published
      /   = post.user.name
    .post-break
      %hr

  .latest-posts-container
    %h2 Latest Hoots
    - @latest_posts.each do |post|
      .post-break
        %hr
      .post-score
        = "#{post.score}"
      .post-comment
        = link_to post.content, post
      .post-comment-stats
        = "Comments: #{post.comment_count} | #{post.user.name}"
      / .post-published
      /   = post.user.name
      / .post-continuous-loading
      /   = render :partial => 'shared/posts', :locals => { :posts => @latest_posts}
    .post-break
      %hr      

  / %h1= link_to "Load More Hoots", posts_path(:page => @latest_posts.next_page), :class => "load-more-posts", :remote => true if @latest_posts.next_page

  
%footer.footer-bar
  %hr
  .footer-link
    = link_to 'New Hoot', new_post_path

  .footer-link-right
    = form_tag searches_path do
      = text_field_tag :query
      = submit_tag "Search"



 

app/views/posts/index.js.haml
$('.posts').append('#{escape_javascript(render partial: "shared/posts", :locals => { :posts => @latest_posts })}');
$('a.load-more-posts').attr('href', '#{posts_path page: @latest_posts.next_page}');
- unless @latest_posts.next_page
  $('a.load-more-posts').remove();

app/views/posts/new.html.haml
%br/
%br/
%br/
%br/
%br/

= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg


  %ul.slides-container    
    %li#new_post
      .post-container
        .post-contrast
          %p#post-text
            Hoot...
  #post-input
    .field#post-text-area
      = f.text_area :content, :size => '30x5', placeholder: "Hoot..."
    .field#post-image-box
      = f.label :image
      = f.file_field :image
      #digits-left Characters left: 141
    .actions
      %input{:type => "submit", :value => "Publish", :class => "button", :id => "post_submit", :content => :content, :name => 'publish'}
      %input{:type => "submit", :value => "Promote", :class => "button", :id => "post_submit", :content => :content, :name => 'promote'}

app/views/posts/show.html.haml
!!!
%html
  %head
  %body.slideshow
    #slides
      %ul.slides-container
        %li
          %img= if @post.image.present? then image_tag @post.image else image_tag randomized_post_image() end
          .slideshow-container
            .slideshow-contrast
              = "#{@post.content} - #{@post.user.name}"

            %ul#comments
              - @post.comments.order("created_at DESC").limit(5).each do |comment|
                %li= "#{comment.content}"

              = form_for [@post, @post.comments.build] do |f|
                %p= f.text_area :content, :size => '30x5', placeholder: "Comment..."

                #digits-left Characters left: 70
                %p= f.submit "Post comment", disabled: true
  :javascript
    $(function() {
      $('#slides').superslides({
        scrollable: false
      });
    });

  %footer.footer-bar
    %hr
    .footer-link
      - if current_user.present?
        = link_to image_tag('PNG/thumbs-up.png', title: "Upvote"), vote_post_path(@post) + "?score=1", method: :put
        = link_to image_tag('PNG/thumbs-down.png',title: "Downvote"), vote_post_path(@post) + "?score=-1", method: :put
        = link_to image_tag('PNG/star.png', title: "Favourite this hoot"), assign_favourite_post_post_path(@post), method: :put
        = link_to image_tag('PNG/heart.png', title: "Favourite this hootster"), assign_favourite_user_user_path(@post.user), method: :put
      
      - if can? :edit, @post
        = link_to image_tag('PNG/info.png', title: "Edit hoot"), edit_post_path(@post)
      
      - if can? :destroy, @post
        = link_to image_tag('PNG/cross.png', title: "Delete hoot"), @post, :method => :delete, :data => { :confirm => 'Are you sure?' }
      .footer-score
        = "Post Score: #{@post.score}"

    .footer-link-right
      = link_to 'View Index', posts_path