config/routes.rb
HootsApp::Application.routes.draw do
  
  devise_for :users, controllers: {:omniauth_callbacks => "omniauth_callbacks"}

  devise_scope :user do
    # get '/users' => 'users#index'
    resources :users, :only => [:index] do
      member do
        get :my_posts
        get :favourites
        put :assign_favourite_user
      end
    end
  end



  root :to => "slideshow#index"

  resources :posts do 
    member do
      put :vote
      put :assign_favourite_post
    end
    resources :comments
  end
  resources :searches, only: [:create]

  # resources :messages, only: [:new, :create]
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HootsApp
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{href: "http://fonts.googleapis.com/css?family=Fenix|Noto+Sans|Droid+Sans|Average+Sans|PT+Sans|Istok+Web|Roboto+Condensed|Roboto:400,300|Doppio+One|Varela+Round|Ruda|Carme|Titillium+Web|Maven+Pro|Vollkorn", rel: "stylesheet", type: "text/css"}/

  %body 
    %header.nav-bar

      - if user_signed_in?
        .nav-link
          = link_to image_tag('/assets/hoots_shadow_logo.png'), root_url

        .nav-link-right
          = link_to 'Logout',  destroy_user_session_path, method: :delete
        .nav-link-right
          \| 
        .nav-link-right
          Logged in as
          = current_user.email
        .nav-link-right
          \|
        .nav-link-right
          = link_to 'Edit Profile', edit_user_registration_path
        .nav-link-right
          \|
        .nav-link-right
          = link_to 'My Favourites', favourites_user_path(current_user)
        .nav-link-right
          \|
        .nav-link-right
          = link_to 'My Hoots', my_posts_user_path(current_user)
        .nav-link-right
          \|
        .nav-link-right
          = link_to 'Leaderboard', users_path


      - else
        .nav-link
          = link_to image_tag('/assets/hoots_shadow_logo.png'), root_url
          / = link_to (image_tag ("app/assets/images/hoots_app_logo_nav_bar_clear_trans.png" "/posts"))
        .nav-link-right
          = link_to 'Sign Up', new_user_registration_path
        .nav-link-right
          \|
        .nav-link-right
          = link_to 'Sign In', new_user_session_path
        .nav-link-right
        /   \|
        / .nav-link-right
        /   = link_to "Sign In With Google", user_omniauth_authorize_path(:google_oauth2)
        / .nav-link-right
        /   \|
        / .nav-link-right  
        /   = link_to "Sign In With Facebook", user_omniauth_authorize_path(:facebook)
      .nav-break
        %hr
      .flash
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}"

    %section    
      = yield